### ISSUE TITLE
Replay Desync for unknown reason

### ISSUE THREAD

**Issue by Istrebitel98** [spazzo966/SpazzoReplayStatKit#18]
Hey! 
I just downloaded the kit and when I try to open the _stats replays, independently of the map they are, the notification of Replay Desync appears. Pretty confident that I'm just missing something. What could that be?
The maps folder is in the same folder as HeroesData and the game, the conversion and the interface have been downloaded today and the maps are from 1 or 2 days ago. 
Thanks in advance!

**Comment by spazzo966** [comment]
I had an error in the latest version with the statistics that caused this to happen - I've just put out a new version that should fix this issue.

If this has fixed it for you, please tell me and I'll close this issue. Thanks.

**Comment by Istrebitel98** [comment]
All perfect now!
Thanks for the work you do!
