### ISSUE TITLE
Is it possible to make a free camera in replays?

### ISSUE THREAD

**Issue by Cruglk** [spazzo966/SpazzoReplayStatKit#20]
Hello!

Thanks for your hard work!

Can you suggest please if there is a possibility in any way while watching replays to change the position of the camera (except for the usual buttons) for the viewer.

Since your code replaces standard maps, where can add own code, is it possible to somehow apply code like:

     CameraSetMouseRotates (EventPlayer(), true);

At the Observer. That is, so that can freely control the camera when watching replays. I believe that such a feature would become very popular.

Or is there a smooth camera for the second viewer (look from the other person's face) - is it possible to access it in order to have a smooth camera movement during single viewing?

Updated.

The camera can be set, but there is only one problem - I don’t know how the viewer's triggering of the function can be adjusted.

For example:

TriggerAddEventKeyPressed
TriggerAddEventChatMessage

They just don't work for the viewer. Can you please tell me if you know if it is possible to launch a function from a viewer's action? Or need to find and launch a free camera with the ability to move (that is not CameraSetMouseRotates, but something else).

**Comment by spazzo966** [comment]
It is not possible to get inputs or even camera position for the observer\replay player, so there's no way to add extra ways to manipulate the camera than Blizzard implemented.

You can press O to view from the perspective of fellow observer slots, though.

**Comment by Cruglk** [comment]
> It is not possible to get inputs or even camera position for the observer\replay player, so there's no way to add extra ways to manipulate the camera than Blizzard implemented.
> 
> You can press O to view from the perspective of fellow observer slots, though.

Thanks for the answer! In fact, the camera can be moved in replay - the only problem is how to teach the camera to turn this mode on and off.

![HeroesOfTheStorm_x64_MPoGKUNGHB](https://user-images.githubusercontent.com/18282051/135700483-2a409fed-de93-4ce9-bdc3-83f0203283e6.jpg)

**Comment by spazzo966** [comment]
There's no way to get inputs from the observer by very design of the engine - I know people have tried with SC2 to no luck.

You can't tell when they've clicked a dialogue option, you can't tell when they've pressed a button, you can't tell where their camera is currently positioned, I've tested these things in the past, even trying something as simple as "is this dialogue visible to observers?" as I had a similar idea to what you want, but nothing worked.

**Comment by Cruglk** [comment]
Thank you so much for your answer! It's a pity that there is no such function in the game. Best wishes to you!
